#include "qthideandshowandthrowdialog.h"

ribi::QtHideAndShowAndThrowDialog::QtHideAndShowAndThrowDialog(QWidget* parent)
  : QtHideAndShowDialog(parent)
{
}

void ribi::QtHideAndShowAndThrowDialog::do_throw()
{
  throw std::runtime_error("Exception generated by QtHideAndShowAndThrowDialog");
}
