language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # R
  - sudo add-apt-repository -y ppa:marutter/rrutter
  - sudo apt-get update -qq

install: 
  # Get my folder
  - my_github=${PWD##*/}  
  # R, do this before 'sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90'
  - sudo apt-get install r-base r-base-dev
  - sudo apt-get install libssh2-1-dev
  - sudo Rscript install_r_packages.R
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # gcov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # BEAST2
  - ./install_beast2
  # Other GitHubs
  - cd ..
  - git clone -b develop https://github.com/richelbilderbeek/boost_graph_cookbook_1
  - git clone -b develop https://github.com/richelbilderbeek/plane
  - git clone -b develop https://github.com/richelbilderbeek/RibiLibraries
  - cd $my_github
  - sudo ./install_other_githubs

# Boost
addons: 
  apt: 
    packages: libboost-all-dev

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  # Console
  - qmake RibiClassesTestConsole.pro
  - make
  - ./RibiClassesTestConsole
  # Desktop
  - qmake RibiClassesTestDesktop.pro
  - make
  - ./RibiClassesTestDesktop
  # cppcheck
  - cppcheck --quiet . # Be mild
  # - cppcheck --quiet --error-exitcode=1 . 
  # Codecov
  - ./get_code_cov.sh > /dev/null
  - codecov > /dev/null
  # OCLint
  - ./do_oclint
